"""Generate the five tutorial notebooks from per-tutorial cell specs.

The `.py` scripts are the source of truth for the tutorial code. The
notebooks wrap that code with narrative markdown and matplotlib plots.
Re-run this file after editing a tutorial to keep the notebooks in sync:

    python examples/_build_notebooks.py
"""

from __future__ import annotations

import json
from pathlib import Path


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": list(lines)}


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": list(lines),
    }


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


NB01 = [
    md(
        "# Tutorial 01 — A dielectric sphere at X-band, checked against Mie\n",
        "\n",
        "A T-matrix solver for nonspherical particles must reduce to classical\n",
        "Mie theory in the `axis_ratio = 1` limit. That reduction is the\n",
        "simplest end-to-end check we can do. This tutorial builds a 1 mm\n",
        "water sphere at X-band, computes its scattering and extinction\n",
        "cross-sections via the T-matrix path, and compares against the\n",
        "closed-form Mie expressions shipped with rustmatrix.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, mie_qsca, mie_qext, scatter\n",
        "from rustmatrix.tmatrix_aux import geom_horiz_back, wl_X\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Build a sphere scatterer at X-band\n"),
    code(
        "radius_mm = 1.0\n",
        "wavelength_mm = wl_X\n",
        "m = m_w_10C[wl_X]\n",
        "\n",
        "s = Scatterer(radius=radius_mm, wavelength=wavelength_mm, m=m,\n",
        "              axis_ratio=1.0, ddelt=1e-4, ndgs=2)\n",
        "s.set_geometry(geom_horiz_back)\n",
        "S, Z = s.get_SZ()\n",
        "S\n",
    ),
    md("## Cross-sections — T-matrix vs Mie\n"),
    code(
        "size_param = 2.0 * np.pi * radius_mm / wavelength_mm\n",
        "sigma_sca_tm = scatter.sca_xsect(s, h_pol=True)\n",
        "sigma_ext_tm = scatter.ext_xsect(s, h_pol=True)\n",
        "\n",
        "geom = np.pi * radius_mm ** 2\n",
        "sigma_sca_mie = mie_qsca(size_param, m.real, m.imag) * geom\n",
        "sigma_ext_mie = mie_qext(size_param, m.real, m.imag) * geom\n",
        "\n",
        "print(f'rel err σ_sca = {abs(sigma_sca_tm-sigma_sca_mie)/sigma_sca_mie:.2e}')\n",
        "print(f'rel err σ_ext = {abs(sigma_ext_tm-sigma_ext_mie)/sigma_ext_mie:.2e}')\n",
    ),
    md("## Q_sca and Q_ext across a size-parameter sweep\n",
       "\n",
       "Plotting both curves side by side makes the Mie ripple pattern\n",
       "visible and confirms that the T-matrix follows it point-for-point.\n"),
    code(
        "xs = np.linspace(0.1, 10.0, 40)\n",
        "q_sca_mie = np.array([mie_qsca(x, m.real, m.imag) for x in xs])\n",
        "q_ext_mie = np.array([mie_qext(x, m.real, m.imag) for x in xs])\n",
        "q_sca_tm = np.empty_like(xs)\n",
        "q_ext_tm = np.empty_like(xs)\n",
        "for i, x in enumerate(xs):\n",
        "    r = x * wavelength_mm / (2.0 * np.pi)\n",
        "    si = Scatterer(radius=r, wavelength=wavelength_mm, m=m,\n",
        "                   axis_ratio=1.0, ddelt=1e-4, ndgs=2)\n",
        "    si.set_geometry(geom_horiz_back)\n",
        "    g = np.pi * r ** 2\n",
        "    q_sca_tm[i] = scatter.sca_xsect(si) / g\n",
        "    q_ext_tm[i] = scatter.ext_xsect(si) / g\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(xs, q_sca_mie, 'k-', label='Q_sca (Mie)')\n",
        "ax.plot(xs, q_ext_mie, 'k--', label='Q_ext (Mie)')\n",
        "ax.plot(xs, q_sca_tm, 'C1o', markersize=4, label='Q_sca (T-matrix)')\n",
        "ax.plot(xs, q_ext_tm, 'C2s', markersize=4, label='Q_ext (T-matrix)')\n",
        "ax.set_xlabel('size parameter  x = 2πr/λ')\n",
        "ax.set_ylabel('efficiency')\n",
        "ax.legend()\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB02 = [
    md(
        "# Tutorial 02 — A single 2 mm raindrop at C-band\n",
        "\n",
        "Falling raindrops are flattened by drag; larger drops are more\n",
        "oblate. Dual-pol radar picks this up as differential reflectivity\n",
        "Z_dr — the ratio of horizontally- to vertically-polarised\n",
        "backscattered power. This notebook computes Z_dr, Z_h, and δ_hv\n",
        "for a single drop and sweeps the axis ratio to show the\n",
        "sensitivity.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Build the drop and evaluate\n"),
    code(
        "D_mm = 2.0\n",
        "axis_ratio = 1.0 / dsr_thurai_2007(D_mm)\n",
        "s = Scatterer(radius=D_mm/2, wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "              axis_ratio=axis_ratio, Kw_sqr=K_w_sqr[wl_C],\n",
        "              ddelt=1e-4, ndgs=2)\n",
        "s.set_geometry(geom_horiz_back)\n",
        "print(f'axis ratio (h/v) = {axis_ratio:.4f}')\n",
        "print(f'Z_h = {10*np.log10(radar.refl(s, True)):.2f} dBZ')\n",
        "print(f'Z_dr = {10*np.log10(radar.Zdr(s)):+.3f} dB')\n",
        "print(f'δ_hv = {np.degrees(radar.delta_hv(s)):+.4f}°')\n",
    ),
    md("## Z_dr across the 0.5–5 mm drop-size range\n"),
    code(
        "Ds = np.linspace(0.5, 5.0, 20)\n",
        "zdrs = np.empty_like(Ds)\n",
        "for i, D in enumerate(Ds):\n",
        "    s.radius = D / 2\n",
        "    s.axis_ratio = 1.0 / dsr_thurai_2007(D)\n",
        "    zdrs[i] = 10 * np.log10(radar.Zdr(s))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(Ds, zdrs, 'C0-o')\n",
        "ax.set_xlabel('equivalent diameter D [mm]')\n",
        "ax.set_ylabel('Z_dr [dB]')\n",
        "ax.set_title('Single-drop Z_dr at C-band (Thurai 2007 shape)')\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB03 = [
    md(
        "# Tutorial 03 — Gamma-PSD rain at C-band\n",
        "\n",
        "Radar volumes sample thousands of drops. The observed Z_h, Z_dr,\n",
        "K_dp, and specific attenuation A_i are PSD-weighted integrals of\n",
        "the single-drop quantities. This notebook tabulates S(D) and Z(D)\n",
        "once, then sweeps the integrated observables across a range of\n",
        "normalised gamma PSDs parameterised by the median volume diameter\n",
        "D0.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar, psd as rs_psd\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C\n",
    ),
    md("## Tabulate once, evaluate many\n"),
    code(
        "s = Scatterer(wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "              Kw_sqr=K_w_sqr[wl_C], ddelt=1e-4, ndgs=2)\n",
        "integ = rs_psd.PSDIntegrator()\n",
        "integ.D_max = 8.0\n",
        "integ.num_points = 64\n",
        "integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "s.psd_integrator = integ\n",
        "s.psd_integrator.init_scatter_table(s)\n",
    ),
    md("## Sweep median diameter D0\n"),
    code(
        "D0s = np.linspace(0.5, 3.0, 12)\n",
        "Zh = np.empty_like(D0s)\n",
        "Zdr = np.empty_like(D0s)\n",
        "Kdp = np.empty_like(D0s)\n",
        "Ai = np.empty_like(D0s)\n",
        "\n",
        "for i, D0 in enumerate(D0s):\n",
        "    s.psd = rs_psd.GammaPSD(D0=D0, Nw=8e3, mu=4)\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    Zh[i] = 10 * np.log10(radar.refl(s))\n",
        "    Zdr[i] = 10 * np.log10(radar.Zdr(s))\n",
        "    s.set_geometry(geom_horiz_forw)\n",
        "    Kdp[i] = radar.Kdp(s)\n",
        "    Ai[i] = radar.Ai(s)\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6), sharex=True)\n",
        "axes[0, 0].plot(D0s, Zh, 'C0-o'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].plot(D0s, Zdr, 'C1-o'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].plot(D0s, Kdp, 'C2-o'); axes[1, 0].set_ylabel('K_dp [°/km]')\n",
        "axes[1, 1].plot(D0s, Ai, 'C3-o'); axes[1, 1].set_ylabel('A_i [dB/km]')\n",
        "for ax in axes.flat:\n",
        "    ax.set_xlabel('D0 [mm]')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "fig.suptitle('C-band gamma-PSD rain observables (Nw=8e3, mu=4)')\n",
        "fig.tight_layout();\n",
    ),
]


NB04 = [
    md(
        "# Tutorial 04 — Oriented ice crystals at W-band\n",
        "\n",
        "Ice crystals fall with a preferred orientation and a spread of\n",
        "canting angles around it. The orientation PDF captures the spread\n",
        "and feeds directly into the dual-pol observables. This notebook\n",
        "compares the three orientation-averaging strategies rustmatrix\n",
        "ships with: none, fixed-quadrature, and adaptive.\n",
    ),
    code(
        "import time\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, orientation as rs_orient, radar\n",
        "from rustmatrix.tmatrix_aux import geom_horiz_back, wl_W\n",
        "from rustmatrix.refractive import mi\n",
    ),
    md("## One crystal, three averaging schemes\n"),
    code(
        "D_eq_mm = 0.5\n",
        "ice_m = mi(wl_W, 0.9)\n",
        "pdf = rs_orient.gaussian_pdf(std=20.0, mean=90.0)\n",
        "base = dict(radius=D_eq_mm/2, wavelength=wl_W, m=ice_m,\n",
        "            axis_ratio=0.5, ddelt=1e-4, ndgs=2)\n",
        "\n",
        "schemes = [\n",
        "    ('single', rs_orient.orient_single, {'or_pdf': pdf}),\n",
        "    ('fixed 6×12', rs_orient.orient_averaged_fixed,\n",
        "     {'or_pdf': pdf, 'n_alpha': 6, 'n_beta': 12}),\n",
        "    ('adaptive', rs_orient.orient_averaged_adaptive, {'or_pdf': pdf}),\n",
        "]\n",
        "rows = []\n",
        "for name, orient, extra in schemes:\n",
        "    s = Scatterer(**base, **extra)\n",
        "    s.orient = orient\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    t0 = time.perf_counter()\n",
        "    zdr = radar.Zdr(s)\n",
        "    elapsed = time.perf_counter() - t0\n",
        "    rows.append((name, 10*np.log10(zdr), elapsed))\n",
        "    print(f'{name:<12} Z_dr = {10*np.log10(zdr):+.4f} dB   ({elapsed*1000:.1f} ms)')\n",
    ),
    md("## Canting-angle spread sensitivity\n",
       "\n",
       "Sweep the Gaussian PDF's `std` parameter to see how rapidly Z_dr\n",
       "collapses as the orientation spread widens.\n"),
    code(
        "stds = np.array([1, 5, 10, 15, 20, 30, 45, 60])\n",
        "zdrs = np.empty_like(stds, dtype=float)\n",
        "for i, sd in enumerate(stds):\n",
        "    s = Scatterer(**base)\n",
        "    s.orient = rs_orient.orient_averaged_fixed\n",
        "    s.or_pdf = rs_orient.gaussian_pdf(std=float(sd), mean=90.0)\n",
        "    s.n_alpha, s.n_beta = 6, 12\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    zdrs[i] = 10 * np.log10(radar.Zdr(s))\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(7, 4))\n",
        "ax.plot(stds, zdrs, 'C0-o')\n",
        "ax.set_xlabel('canting-angle σ [deg]')\n",
        "ax.set_ylabel('Z_dr [dB]')\n",
        "ax.set_title('W-band prolate ice column, oriented')\n",
        "ax.grid(True, alpha=0.3)\n",
        "fig.tight_layout();\n",
    ),
]


NB05 = [
    md(
        "# Tutorial 05 — One PSD, six radar bands\n",
        "\n",
        "Retrieval algorithms that use more than one frequency need a\n",
        "forward model that works across the whole instrument suite. This\n",
        "notebook runs the same moderate-convective gamma PSD through\n",
        "rustmatrix at S, C, X, Ku, Ka, and W band and plots the frequency\n",
        "response of the dual-pol observables.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, radar, psd as rs_psd\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr,\n",
        "                                      wl_S, wl_C, wl_X, wl_Ku,\n",
        "                                      wl_Ka, wl_W)\n",
        "from rustmatrix.refractive import m_w_20C\n",
        "\n",
        "BANDS = [('S', wl_S), ('C', wl_C), ('X', wl_X),\n",
        "         ('Ku', wl_Ku), ('Ka', wl_Ka), ('W', wl_W)]\n",
    ),
    md("## Run the six bands\n"),
    code(
        "def run(wl):\n",
        "    s = Scatterer(wavelength=wl, m=m_w_20C[wl],\n",
        "                  Kw_sqr=K_w_sqr[wl], ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 8.0\n",
        "    integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = rs_psd.GammaPSD(D0=1.5, Nw=8e3, mu=4)\n",
        "    s.set_geometry(geom_horiz_back)\n",
        "    Zh = 10 * np.log10(radar.refl(s))\n",
        "    Zdr = 10 * np.log10(radar.Zdr(s))\n",
        "    s.set_geometry(geom_horiz_forw)\n",
        "    return Zh, Zdr, radar.Kdp(s), radar.Ai(s)\n",
        "\n",
        "Zh = {}; Zdr = {}; Kdp = {}; Ai = {}\n",
        "for name, wl in BANDS:\n",
        "    Zh[name], Zdr[name], Kdp[name], Ai[name] = run(wl)\n",
        "    print(f'{name:<3} Z_h={Zh[name]:6.2f}  Z_dr={Zdr[name]:+.3f}  '\n",
        "          f'K_dp={Kdp[name]:+.3f}  A_i={Ai[name]:.4f}')\n",
    ),
    md("## Plot the frequency response\n"),
    code(
        "names = [b[0] for b in BANDS]\n",
        "wls = np.array([b[1] for b in BANDS])\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6))\n",
        "axes[0, 0].semilogx(wls, [Zh[n] for n in names], 'o-'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].semilogx(wls, [Zdr[n] for n in names], 'o-'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].semilogx(wls, [Kdp[n] for n in names], 'o-'); axes[1, 0].set_ylabel('K_dp [°/km]')\n",
        "axes[1, 1].semilogx(wls, [Ai[n] for n in names], 'o-'); axes[1, 1].set_ylabel('A_i [dB/km]')\n",
        "for ax, label in zip(axes.flat, names*4):\n",
        "    ax.set_xlabel('wavelength [mm]')\n",
        "    ax.grid(True, alpha=0.3, which='both')\n",
        "    for name, wl in BANDS:\n",
        "        ax.axvline(wl, color='k', alpha=0.1)\n",
        "fig.suptitle('Moderate convective rain (D0=1.5 mm): frequency response')\n",
        "fig.tight_layout();\n",
    ),
]


NB06 = [
    md(
        "# Tutorial 06 — Hydrometeor mixtures at C-band\n",
        "\n",
        "Real radar volumes sometimes contain more than a single species —\n",
        "rain with melting ice, pristine crystals with aggregates, graupel\n",
        "in the mixed phase. The combined polarimetric signature is the\n",
        "incoherent sum of the per-species S and Z matrices; the\n",
        "*non*-linear observables (Z_dr, ρ_hv, δ_hv) cannot be averaged\n",
        "from per-species values and must be computed from the mixture's\n",
        "summed amplitude and phase matrices.\n",
        "\n",
        "`HydroMix` takes a list of `MixtureComponent(Scatterer, PSD)` pairs\n",
        "and exposes a Scatterer-shaped API so the usual `radar.*` helpers\n",
        "work on it directly.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import (HydroMix, MixtureComponent,\n",
        "                         Scatterer, radar, psd as rs_psd)\n",
        "from rustmatrix.tmatrix_aux import (dsr_thurai_2007, geom_horiz_back,\n",
        "                                      geom_horiz_forw, K_w_sqr, wl_C)\n",
        "from rustmatrix.refractive import m_w_10C, mi\n",
    ),
    md("## Build one scatterer per species\n",
       "\n",
       "Each species gets its own `PSDIntegrator` that tabulates S(D)\n",
       "and Z(D) for whatever refractive index, axis ratio, and orientation\n",
       "PDF the species requires. All integrators must register the same\n",
       "geometries the mixture will query and must share the wavelength.\n"),
    code(
        "def build_rain():\n",
        "    s = Scatterer(wavelength=wl_C, m=m_w_10C[wl_C],\n",
        "                  Kw_sqr=K_w_sqr[wl_C], ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 6.0; integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    return s\n",
        "\n",
        "def build_ice():\n",
        "    s = Scatterer(wavelength=wl_C, m=mi(wl_C, 0.2),\n",
        "                  Kw_sqr=K_w_sqr[wl_C], axis_ratio=0.6,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = rs_psd.PSDIntegrator()\n",
        "    integ.D_max = 8.0; integ.num_points = 64\n",
        "    integ.geometries = (geom_horiz_back, geom_horiz_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    return s\n",
        "\n",
        "rain = build_rain(); ice = build_ice()\n",
        "rain_psd = rs_psd.GammaPSD(D0=1.5, Nw=8e3, mu=4, D_max=6.0)\n",
        "ice_psd  = rs_psd.ExponentialPSD(N0=5e3, Lambda=2.0, D_max=8.0)\n",
        "rain.psd = rain_psd; ice.psd = ice_psd\n",
    ),
    md("## Assemble the mixture and read the observables\n"),
    code(
        "mix = HydroMix([\n",
        "    MixtureComponent(rain, rain_psd, 'rain'),\n",
        "    MixtureComponent(ice,  ice_psd,  'ice'),\n",
        "])\n",
        "\n",
        "def obs(x):\n",
        "    x.set_geometry(geom_horiz_back)\n",
        "    out = dict(Zh=10*np.log10(radar.refl(x)),\n",
        "               Zdr=10*np.log10(radar.Zdr(x)),\n",
        "               rho=radar.rho_hv(x))\n",
        "    x.set_geometry(geom_horiz_forw)\n",
        "    out['Kdp'] = radar.Kdp(x); out['Ai'] = radar.Ai(x)\n",
        "    return out\n",
        "\n",
        "for name, obj in [('rain only', rain),\n",
        "                  ('ice only',  ice),\n",
        "                  ('mixture',   mix)]:\n",
        "    o = obs(obj)\n",
        "    print(f'{name:<12} Z_h={o[\"Zh\"]:6.2f}  Z_dr={o[\"Zdr\"]:+.3f}  '\n",
        "          f'ρ_hv={o[\"rho\"]:.5f}  K_dp={o[\"Kdp\"]:+.3f}  A_i={o[\"Ai\"]:.4f}')\n",
    ),
    md("## Sweep the ice fraction\n",
       "\n",
       "Scale the ice PSD's N0 from zero up to the rain contribution and\n",
       "watch Z_dr, ρ_hv, and K_dp interpolate between the rain-only and\n",
       "ice-heavy limits. Because both S and Z are linear in N(D), this\n",
       "is exactly the behaviour predicted by incoherent mixing.\n"),
    code(
        "N0_ice_sweep = np.linspace(0.0, 2e4, 9)\n",
        "Zh_sw, Zdr_sw, rho_sw, Kdp_sw = [], [], [], []\n",
        "for N0 in N0_ice_sweep:\n",
        "    ice_psd_sw = rs_psd.ExponentialPSD(N0=float(N0), Lambda=2.0, D_max=8.0)\n",
        "    m_sw = HydroMix([\n",
        "        MixtureComponent(rain, rain_psd, 'rain'),\n",
        "        MixtureComponent(ice,  ice_psd_sw, 'ice'),\n",
        "    ])\n",
        "    o = obs(m_sw)\n",
        "    Zh_sw.append(o['Zh']); Zdr_sw.append(o['Zdr'])\n",
        "    rho_sw.append(o['rho']); Kdp_sw.append(o['Kdp'])\n",
        "\n",
        "fig, axes = plt.subplots(2, 2, figsize=(9, 6), sharex=True)\n",
        "axes[0, 0].plot(N0_ice_sweep, Zh_sw,  'C0-o'); axes[0, 0].set_ylabel('Z_h [dBZ]')\n",
        "axes[0, 1].plot(N0_ice_sweep, Zdr_sw, 'C1-o'); axes[0, 1].set_ylabel('Z_dr [dB]')\n",
        "axes[1, 0].plot(N0_ice_sweep, rho_sw, 'C2-o'); axes[1, 0].set_ylabel('ρ_hv')\n",
        "axes[1, 1].plot(N0_ice_sweep, Kdp_sw, 'C3-o'); axes[1, 1].set_ylabel('K_dp [°/km]')\n",
        "for ax in axes.flat:\n",
        "    ax.set_xlabel('ice N₀ [m⁻³ mm⁻¹]')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "fig.suptitle('C-band rain + oriented ice — sweeping the ice concentration')\n",
        "fig.tight_layout();\n",
    ),
]


NB07 = [
    md(
        "# Tutorial 07 — Doppler + polarimetric spectra of rain at X-band\n",
        "\n",
        "Profilers, cloud radars, and modern disdrometers measure *spectra*\n",
        "— the Doppler-velocity-resolved version of the polarimetric\n",
        "observables. The spectrum of a falling rain PSD is a change of\n",
        "variable from drop diameter to terminal velocity, convolved with\n",
        "turbulence and smeared by finite antenna beamwidth. This notebook\n",
        "walks through the four knobs that shape the spectrum and checks\n",
        "that the integrated spectral matrices round-trip to the bulk\n",
        "`radar.*` observables.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import Scatterer, SpectralIntegrator, radar, spectra\n",
        "from rustmatrix.psd import GammaPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_10C\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, dsr_thurai_2007,\n",
        "                                      geom_vert_back, geom_vert_forw,\n",
        "                                      wl_X)\n",
    ),
    md("## Build an X-band rain scatterer with vertical-pointing geometry\n"),
    code(
        "def build_rain():\n",
        "    s = Scatterer(wavelength=wl_X, m=m_w_10C[wl_X],\n",
        "                  Kw_sqr=K_w_sqr[wl_X], ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = 6.0\n",
        "    integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_vert_back, geom_vert_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = GammaPSD(D0=1.5, Nw=8e3, mu=4, D_max=6.0)\n",
        "    return s\n",
        "\n",
        "rain = build_rain()\n",
    ),
    md("## Four configurations of the spectrum\n",
       "\n",
       "1. No turbulence, no beam broadening — delta-function binning.\n",
       "2. Gaussian turbulence σ = 0.5 m/s — classical broadening.\n",
       "3. Zeng 2023 particle-inertia turbulence.\n",
       "4. Beam broadening with u_h = 8 m/s and θ_b = 1°.\n"),
    code(
        "def run_config(turbulence, u_h=0.0, beamwidth=0.0):\n",
        "    integ = SpectralIntegrator(\n",
        "        rain,\n",
        "        fall_speed=spectra.fall_speed.atlas_srivastava_sekhon_1973,\n",
        "        turbulence=turbulence,\n",
        "        v_min=-1.0, v_max=12.0, n_bins=1024,\n",
        "        u_h=u_h, beamwidth=beamwidth,\n",
        "        geometry_backscatter=geom_vert_back,\n",
        "        geometry_forward=geom_vert_forw,\n",
        "    )\n",
        "    return integ.run()\n",
        "\n",
        "configs = {\n",
        "    'no turbulence': run_config(spectra.NoTurbulence()),\n",
        "    'Gaussian σ=0.5': run_config(spectra.GaussianTurbulence(0.5)),\n",
        "    'Zeng 2023 ε=1e-3': run_config(\n",
        "        spectra.InertialZeng2023(sigma_air=0.5, epsilon=1e-3)),\n",
        "    'beam (u_h=8, θ_b=1°)': run_config(\n",
        "        spectra.NoTurbulence(),\n",
        "        u_h=8.0, beamwidth=np.deg2rad(1.0)),\n",
        "}\n",
        "\n",
        "rain.set_geometry(geom_vert_back)\n",
        "Zh_bulk = radar.refl(rain)\n",
        "for name, res in configs.items():\n",
        "    Zh_int = np.trapezoid(res.sZ_h, res.v)\n",
        "    print(f'{name:<24} ∫sZ_h dv / Z_h_bulk - 1 = '\n",
        "          f'{(Zh_int - Zh_bulk) / Zh_bulk:+.2e}')\n",
    ),
    md("## Plot sZ_h(v) for the four configurations\n"),
    code(
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "for name, res in configs.items():\n",
        "    ax.plot(res.v, res.sZ_h, label=name)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [mm⁶ m⁻³ / (m/s)]')\n",
        "ax.set_xlim(0, 12)\n",
        "ax.legend()\n",
        "ax.grid(True, alpha=0.3)\n",
        "ax.set_title('X-band rain spectrum — turbulence and beam-broadening knobs')\n",
        "fig.tight_layout();\n",
    ),
    md("## Optional system noise\n",
       "\n",
       "Receiver noise biases sZ_dr and sρ_hv in real observations. Pass\n",
       "`noise=\"realistic\"` to bake in a sensible noise floor; the\n",
       "underlying S_spec / Z_spec stay signal-only so `collapse_to_bulk()`\n",
       "still round-trips exactly.\n"),
    code(
        "noisy = SpectralIntegrator(\n",
        "    rain,\n",
        "    fall_speed=spectra.fall_speed.atlas_srivastava_sekhon_1973,\n",
        "    turbulence=spectra.GaussianTurbulence(0.3),\n",
        "    v_min=-1.0, v_max=12.0, n_bins=1024,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        "    noise='realistic',\n",
        ").run()\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 4))\n",
        "ax.semilogy(noisy.v, noisy.sZ_h, 'C0-', label='signal + noise')\n",
        "ax.axhline(noisy.noise_h / (noisy.v[-1] - noisy.v[0]),\n",
        "           color='k', ls='--', alpha=0.6, label='noise floor')\n",
        "ax.set_xlim(0, 12)\n",
        "ax.set_xlabel('Doppler velocity v [m/s]')\n",
        "ax.set_ylabel('sZ_h [mm⁶ m⁻³ / (m/s)]')\n",
        "ax.legend(); ax.grid(True, which='both', alpha=0.3)\n",
        "ax.set_title(f'Realistic noise floor: total noise = {noisy.noise_h:.3g} mm⁶/m³')\n",
        "fig.tight_layout();\n",
    ),
    md("## Bulk ↔ spectrum round-trip\n",
       "\n",
       "`SpectralResult.collapse_to_bulk()` integrates S_spec and Z_spec over\n",
       "velocity, yielding a Scatterer-shaped shim that the bulk `radar.*`\n",
       "helpers read. Non-linear observables (Z_dr, ρ_hv) must be derived\n",
       "from the *summed* matrices — not from averaging the spectral values.\n"),
    code(
        "res = run_config(spectra.GaussianTurbulence(0.3))\n",
        "bulk = res.collapse_to_bulk()\n",
        "rain.set_geometry(geom_vert_back)\n",
        "print(f'Z_h  spectrum = {10*np.log10(radar.refl(bulk)):.3f} dBZ   '\n",
        "      f'bulk = {10*np.log10(radar.refl(rain)):.3f} dBZ')\n",
        "print(f'Z_dr spectrum = {10*np.log10(radar.Zdr(bulk)):+.3f} dB    '\n",
        "      f'bulk = {10*np.log10(radar.Zdr(rain)):+.3f} dB')\n",
        "print(f'ρ_hv spectrum = {radar.rho_hv(bulk):.5f}      '\n",
        "      f'bulk = {radar.rho_hv(rain):.5f}')\n",
    ),
]


NB08 = [
    md(
        "# Tutorial 08 — Spectral polarimetry of a rain + ice mixture\n",
        "\n",
        "Rain falls at ~5 m/s; unrimed aggregates at ~1 m/s. In mixed-phase\n",
        "volumes the two populations show up as distinct *modes* in the\n",
        "Doppler spectrum. The magic of spectral polarimetry is that each\n",
        "velocity bin carries its own sZ_dr(v), sρ_hv(v), and sδ_hv(v), so\n",
        "the two components can be diagnosed separately even when the bulk\n",
        "observables average them together.\n",
        "\n",
        "`HydroMix` + `SpectralIntegrator` handle this natively: each\n",
        "component gets its own fall-speed and turbulence model, and the\n",
        "integrator sums per-component spectra on a shared velocity grid.\n",
    ),
    code(
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "from rustmatrix import (HydroMix, MixtureComponent, Scatterer,\n",
        "                         SpectralIntegrator, radar, spectra)\n",
        "from rustmatrix.psd import ExponentialPSD, GammaPSD, PSDIntegrator\n",
        "from rustmatrix.refractive import m_w_10C, mi\n",
        "from rustmatrix.tmatrix_aux import (K_w_sqr, dsr_thurai_2007,\n",
        "                                      geom_vert_back, geom_vert_forw,\n",
        "                                      wl_X)\n",
    ),
    md("## Build rain and low-density ice scatterers\n"),
    code(
        "def build_rain():\n",
        "    s = Scatterer(wavelength=wl_X, m=m_w_10C[wl_X],\n",
        "                  Kw_sqr=K_w_sqr[wl_X], ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = 6.0; integ.num_points = 64\n",
        "    integ.axis_ratio_func = lambda D: 1.0 / dsr_thurai_2007(D)\n",
        "    integ.geometries = (geom_vert_back, geom_vert_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = GammaPSD(D0=1.5, Nw=8e3, mu=4, D_max=6.0)\n",
        "    return s\n",
        "\n",
        "def build_ice():\n",
        "    s = Scatterer(wavelength=wl_X, m=mi(wl_X, 0.2),\n",
        "                  Kw_sqr=K_w_sqr[wl_X], axis_ratio=0.6,\n",
        "                  ddelt=1e-4, ndgs=2)\n",
        "    integ = PSDIntegrator()\n",
        "    integ.D_max = 8.0; integ.num_points = 64\n",
        "    integ.geometries = (geom_vert_back, geom_vert_forw)\n",
        "    s.psd_integrator = integ\n",
        "    s.psd_integrator.init_scatter_table(s)\n",
        "    s.psd = ExponentialPSD(N0=5e3, Lambda=2.0, D_max=8.0)\n",
        "    return s\n",
        "\n",
        "rain = build_rain(); ice = build_ice()\n",
    ),
    md("## Assemble the mixture and run the spectral integrator\n"),
    code(
        "mix = HydroMix([\n",
        "    MixtureComponent(rain, rain.psd, 'rain'),\n",
        "    MixtureComponent(ice,  ice.psd,  'ice'),\n",
        "])\n",
        "\n",
        "integ = SpectralIntegrator(\n",
        "    mix,\n",
        "    component_kinematics={\n",
        "        'rain': (spectra.fall_speed.atlas_srivastava_sekhon_1973,\n",
        "                 spectra.GaussianTurbulence(0.2)),\n",
        "        'ice':  (spectra.fall_speed.locatelli_hobbs_1974_aggregates,\n",
        "                 spectra.GaussianTurbulence(0.2)),\n",
        "    },\n",
        "    v_min=-1.0, v_max=12.0, n_bins=1024,\n",
        "    geometry_backscatter=geom_vert_back,\n",
        "    geometry_forward=geom_vert_forw,\n",
        ")\n",
        "res = integ.run()\n",
        "\n",
        "ice_mask = res.v < 2.0\n",
        "rain_mask = res.v > 2.0\n",
        "v_ice  = res.v[ice_mask][np.argmax(res.sZ_h[ice_mask])]\n",
        "v_rain = res.v[rain_mask][np.argmax(res.sZ_h[rain_mask])]\n",
        "valley_mask = (res.v > v_ice) & (res.v < v_rain)\n",
        "v_valley = res.v[valley_mask][np.argmin(res.sZ_h[valley_mask])]\n",
        "print(f'ice-mode peak  : v = {v_ice:.2f} m/s')\n",
        "print(f'rain-mode peak : v = {v_rain:.2f} m/s')\n",
        "print(f'inter-mode valley: v = {v_valley:.2f} m/s')\n",
    ),
    md("## Plot the bimodal spectrum\n",
       "\n",
       "`sZ_h(v)` shows the two modes clearly; the sZ_dr trace is flat at\n",
       "vertical pointing (H and V are symmetric for axisymmetric particles\n",
       "along the vertical axis), which is exactly the behaviour bulk Z_dr\n",
       "has at that geometry.\n"),
    code(
        "fig, (a1, a2) = plt.subplots(2, 1, figsize=(8, 6), sharex=True)\n",
        "a1.semilogy(res.v, np.maximum(res.sZ_h, 1e-10), 'C0-')\n",
        "a1.axvline(v_ice,   color='C2', alpha=0.5, label=f'ice  peak ({v_ice:.2f})')\n",
        "a1.axvline(v_rain,  color='C3', alpha=0.5, label=f'rain peak ({v_rain:.2f})')\n",
        "a1.axvline(v_valley, color='k', ls='--', alpha=0.5,\n",
        "           label=f'valley ({v_valley:.2f})')\n",
        "a1.set_ylabel('sZ_h [mm⁶ m⁻³ / (m/s)]')\n",
        "a1.legend(); a1.grid(True, which='both', alpha=0.3)\n",
        "\n",
        "a2.plot(res.v, res.srho_hv, 'C1-')\n",
        "a2.set_ylabel('sρ_hv')\n",
        "a2.set_xlabel('Doppler velocity v [m/s]')\n",
        "a2.grid(True, alpha=0.3)\n",
        "a2.set_xlim(-1, 12)\n",
        "fig.suptitle('X-band rain + ice: bimodal Doppler spectrum')\n",
        "fig.tight_layout();\n",
    ),
    md("## Bulk round-trip through collapse_to_bulk\n"),
    code(
        "bulk = res.collapse_to_bulk()\n",
        "mix.set_geometry(geom_vert_back)\n",
        "print(f'Z_h  bulk = {10*np.log10(radar.refl(mix)):.3f} dBZ   '\n",
        "      f'spectrum = {10*np.log10(radar.refl(bulk)):.3f} dBZ')\n",
        "print(f'Z_dr bulk = {10*np.log10(radar.Zdr(mix)):+.3f} dB    '\n",
        "      f'spectrum = {10*np.log10(radar.Zdr(bulk)):+.3f} dB')\n",
        "print(f'ρ_hv bulk = {radar.rho_hv(mix):.5f}       '\n",
        "      f'spectrum = {radar.rho_hv(bulk):.5f}')\n",
    ),
]


def main() -> None:
    here = Path(__file__).parent
    for name, cells in (("01_sphere_mie.ipynb", NB01),
                        ("02_raindrop_zdr.ipynb", NB02),
                        ("03_psd_gamma_rain.ipynb", NB03),
                        ("04_oriented_ice.ipynb", NB04),
                        ("05_radar_band_sweep.ipynb", NB05),
                        ("06_hd_mix.ipynb", NB06),
                        ("07_doppler_spectrum_rain.ipynb", NB07),
                        ("08_spectral_polarimetry_rain_ice.ipynb", NB08)):
        path = here / name
        with open(path, "w") as f:
            json.dump(notebook(cells), f, indent=1)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
